# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-07 09:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def data_migration(apps, schema_editor):
    SystemUser = apps.get_model('system_auth', 'SystemUser')
    Account = apps.get_model('account', 'Account')

    accounts = []
    for user in SystemUser.objects.all():
        accounts.append(Account(user=user))

    Account.objects.bulk_create(accounts)


def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(data_migration, rollback),

        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('transfer_type', models.SmallIntegerField(choices=[(1, 'Put'), (2, 'Withdraw')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='account.Account')),
            ],
        ),
    ]
