# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def data_migration(apps, schema_editor):
    Account = apps.get_model('account', 'Account')
    Currency = apps.get_model('currencies', 'Currency')
    default_currency = Currency.objects.get(name="USD")
    Account.objects.all().update(currency=default_currency)


def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='currencies.Currency'),
        ),

        migrations.RunPython(data_migration, rollback),

        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='currencies.Currency'),
        ),
    ]
