# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-15 06:05
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations, models


def install_fixtures(apps, schema_editor):
    call_command('loaddata', 'fixtures/dealing_center_settings.json')


def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),

        migrations.RunPython(install_fixtures, rollback)
    ]
