# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 14:45
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion


def install_fixtures(apps, schema_editor):
    call_command('loaddata', 'fixtures/currencies.json')


def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('full_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_where_base', to='currencies.Currency')),
                ('quoted_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_where_quoted', to='currencies.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPairValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_values', to='currencies.CurrencyPair')),
            ],
            options={
                'ordering': ('-creation_time',),
            },
        ),

        migrations.RunPython(install_fixtures, rollback)
    ]
