# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_auto_20161113_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPairValueHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('creation_time', models.DateTimeField()),
                ('period', models.SmallIntegerField(choices=[(1, '5 minutes'), (2, '15 minutes'), (3, '30 minutes'), (4, '1 hour'), (5, '4 hours'), (6, '1 day'), (7, '1 week')])),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_values_history', to='currencies.CurrencyPair')),
            ],
            options={
                'ordering': ('-creation_time',),
            },
        ),
        migrations.AlterField(
            model_name='currencypairvalue',
            name='creation_time',
            field=models.DateTimeField(),
        ),
    ]
