# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-20 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='answer_secret_question',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='second name'),
        ),
    ]
