# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_auth', '0003_auto_20161120_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='systemuser',
            name='secret_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_auth.SecretQuestion'),
        ),
    ]
