# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-13 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Opened'), (2, 'Closed')])),
                ('type', models.SmallIntegerField(choices=[(1, 'Long'), (2, 'Short')])),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('amount', models.FloatField()),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.CurrencyPair')),
                ('end_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_value', to='currencies.CurrencyPairValue')),
                ('start_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_value', to='currencies.CurrencyPairValue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
