# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'buy'), (2, 'sell')]),
        ),
    ]
