# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 20:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20161120_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(validators=django.core.validators.MinValueValidator(0.01)),
        ),
    ]
