# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-01 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20161129_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
